/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.jlawal.rootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFsiO1qbWJOqSU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFsiO1qbWJOqSU= >>
// ----------- >>
public class HairStyle {
  // ----------- << attribute.annotations@AAAAAAFsiPTED2S1HjU= >>
  // ----------- >>
  private Integer hairstyleId;

  // ----------- << attribute.annotations@AAAAAAFsiPT772Thseo= >>
  // ----------- >>
  private String hairstyleName;

  // ----------- << attribute.annotations@AAAAAAFsiPU132UE/YY= >>
  // ----------- >>
  private String imageUrl;

  private Integer getHairstyleId() {
    return hairstyleId;
  }

  private String getHairstyleName() {
    return hairstyleName;
  }

  private String getImageUrl() {
    return imageUrl;
  }

  private void setHairstyleId(Integer hairstyleId) {
    this.hairstyleId = hairstyleId;
  }

  private void setHairstyleName(String hairstyleName) {
    this.hairstyleName = hairstyleName;
  }

  private void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

// ----------- << class.extras@AAAAAAFsiO1qbWJOqSU= >>
// ----------- >>
}