/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.jlawal.rootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFsiOxdx2HxIXA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFsiOxdx2HxIXA= >>
// ----------- >>
public class Review {
  // ----------- << attribute.annotations@AAAAAAFsiPs4XXbHqw0= >>
  // ----------- >>
  private Integer reviewId;

  // ----------- << attribute.annotations@AAAAAAFsiPt/pHc7S5I= >>
  // ----------- >>
  private String reviewDescription;

  // ----------- << attribute.annotations@AAAAAAFsiPylEXhBf3c= >>
  // ----------- >>
  private String reviewRating;

  // ----------- << attribute.annotations@AAAAAAFsiP0S33j1DrE= >>
  // ----------- >>
  private DateTime dateOfReview;

  // ----------- << attribute.annotations@AAAAAAFsiP3PW3l99po= >>
  // ----------- >>
  private User ;

  private Integer getReviewId() {
    return reviewId;
  }

  private String getReviewDescription() {
    return reviewDescription;
  }

  private String getReviewRating() {
    return reviewRating;
  }

  private DateTime getDateOfReview() {
    return dateOfReview;
  }

  public User get() {
    return ;
  }

  private void setReviewId(Integer reviewId) {
    this.reviewId = reviewId;
  }

  private void setReviewDescription(String reviewDescription) {
    this.reviewDescription = reviewDescription;
  }

  private void setReviewRating(String reviewRating) {
    this.reviewRating = reviewRating;
  }

  private void setDateOfReview(DateTime dateOfReview) {
    this.dateOfReview = dateOfReview;
  }

  public void set(User ) {
    this. = ;
  }

  public void link(User _) {
    set(_);
  }

  public void unlink() {
    set(null);
  }

// ----------- << class.extras@AAAAAAFsiOxdx2HxIXA= >>
// ----------- >>
}