/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.jlawal.rootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFsiOxAKWF210I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFsiOxAKWF210I= >>
// ----------- >>
public class ServiceTime {
  // ----------- << attribute.annotations@AAAAAAFsiQQiyYcKjSw= >>
  // ----------- >>
  private Integer timeId;

  // ----------- << attribute.annotations@AAAAAAFsiQXMGIg/DRM= >>
  // ----------- >>
  private Time startTime;

  // ----------- << attribute.annotations@AAAAAAFsiQlMt4kac+k= >>
  // ----------- >>
  private Time endTime;

  // ----------- << attribute.annotations@AAAAAAFsiTCih6lkkp4= >>
  // ----------- >>
  private Set<Seat>  = new HashSet<>();

  private Integer getTimeId() {
    return timeId;
  }

  private Time getStartTime() {
    return startTime;
  }

  private Time getEndTime() {
    return endTime;
  }

  public Set<Seat> get() {
    return ;
  }

  private void setTimeId(Integer timeId) {
    this.timeId = timeId;
  }

  private void setStartTime(Time startTime) {
    this.startTime = startTime;
  }

  private void setEndTime(Time endTime) {
    this.endTime = endTime;
  }

  public void link(Seat _) {
    if (_ != null) {
      get().add(_);
    }
  }

  public void unlink(Seat _) {
    if (_ != null) {
      get().remove(_);
    }
  }

  public void unlink(Iterator<Seat> it) {
    it.remove();
  }

// ----------- << class.extras@AAAAAAFsiOxAKWF210I= >>
// ----------- >>
}